StudentQuiz: There are some issues of Add completion criteria #732619
studentquiz/moodle-mod_studentquiz pull request #474
Opened 2023-10-27 07:42 UTC by BruceGoodGuy

2023-10-27 07:44 UTC, BruceGoodGuy commented
Hi @timhunt,

Please help me to review my code changes. thanks so much.
Commit ID: [7b1dd5d05f46892afa92fb8d10bb09172beaefe0](https://github.com/studentquiz/moodle-mod_studentquiz/pull/474/commits/7b1dd5d05f46892afa92fb8d10bb09172beaefe0)

2023-10-27 15:02 UTC, timhunt requested changes

2023-10-27 15:02 UTC, timhunt commented on tests/custom_completion_test.php
> +        $status = $customcompletion::update_state($course, $cm, $user->id);
This is a static method. The call should be custom_completion::update_state, with no need to create an instance.

2023-10-27 15:02 UTC, timhunt commented on tests/custom_completion_test.php
> +                1,
Why are you using magic numbers here, and not the constants like COMPLETION_TRACKING_MANUAL ?

2023-11-01 03:19 UTC, BruceGoodGuy commented
Hi @timhunt ,

Thanks for your feedback.

In this commit, I have made two changes:

1. Rename the function update_state to trigger_completion_state_update.

2. Rewrite unit-test for the function trigger_completion_state_update.
Could you help me to review it again? Thanks so much.
Commit ID:  [43e361d85e74fad36a4dee561fd338004a757326](https://github.com/studentquiz/moodle-mod_studentquiz/pull/474/commits/43e361d85e74fad36a4dee561fd338004a757326)

2023-11-01 17:01 UTC, merged

2023-11-01 17:01 UTC, timhunt commented
Thanks. Merged.